name: helper
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  auto_route: ^8.1.3
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_analytics: ^10.10.5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  intl: null
  logger: ^2.0.2+1
  lottie: ^2.7.0
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0
  sizer: ^2.0.15
  upgrader: ^10.3.0
  url_launcher: ^6.2.1

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  injectable_generator: ^2.4.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/gen/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/gen/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
