name: helper
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  auto_route: ^10.1.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  equatable: ^2.0.7
  firebase_analytics: ^12.0.2
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.1
  get_it: ^8.2.0
  google_fonts: ^6.3.2
  injectable: ^2.5.1
  intl: ^0.20.2
  logger: ^2.6.1
  lottie: ^3.3.2
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  sizer: ^3.1.3
  upgrader: ^12.1.0
  url_launcher: ^6.3.2


dev_dependencies:
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1
  drift_dev: ^2.28.3
  fluttertest: ^0.0.1
  injectable_generator: ^2.8.1
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gen/lottie/

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/gen/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
