name: zawj
description: A new Flutter project.

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_analytics: ^10.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  shimmer: ^3.0.0
  sizer: ^2.0.15
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  injectable_generator: ^2.4.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
