// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4PSF31RsvMXveZZbTz5zRmbn1jT1v7lU',
    appId: '1:934419636436:web:8bf53d75b31cdca9011b41',
    messagingSenderId: '934419636436',
    projectId: 'frzbi-69479',
    authDomain: 'frzbi-69479.firebaseapp.com',
    storageBucket: 'frzbi-69479.appspot.com',
    measurementId: 'G-B6S8FQZC6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtO2Y4vrg3whSnzzwQdXZFyXFlU5PlIY4',
    appId: '1:934419636436:android:4ae8a4f88238819f011b41',
    messagingSenderId: '934419636436',
    projectId: 'frzbi-69479',
    storageBucket: 'frzbi-69479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFcXmNncnoQKlMlIwTO-c4xkRb39dE_UM',
    appId: '1:934419636436:ios:3bcb3a2ae7cfe7ab011b41',
    messagingSenderId: '934419636436',
    projectId: 'frzbi-69479',
    storageBucket: 'frzbi-69479.appspot.com',
    iosBundleId: 'com.shopxco.frzbi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFcXmNncnoQKlMlIwTO-c4xkRb39dE_UM',
    appId: '1:934419636436:ios:a40e011abcd4415b011b41',
    messagingSenderId: '934419636436',
    projectId: 'frzbi-69479',
    storageBucket: 'frzbi-69479.appspot.com',
    iosBundleId: 'com.shopxco.frzbi.RunnerTests',
  );
}
